### ISSUE TITLE
KerbalEVA.OnVesselGoOnRails NullReferenceException

### ISSUE THREAD

**Issue by BrettRyland** [KSPModdingLibs/KSPCommunityFixes#77]
When switching to a packed vessel with an EVA kerbal (for example by spawning a group of vessels with BDArmory where one of the craft has an external combat seat (which is a modified command seat)), I'm getting a null reference exception caused by one of the patches in this mod (it doesn't occur when KSPCF isn't installed).
The section of the KSP.log surrounding the exception is:
```
[LOG 00:18:02.243] [BDArmory.VesselSpawnerBase]: Vessel Microraptor AIM-9 spawned!
[LOG 00:18:02.243] [BDArmory.VesselSpawnerBase]: Vessel Microraptor Turret spawned!
[LOG 00:18:02.244] [BDArmory.VesselSpawnerBase]: Vessel Hang-time (wood) v3 spawned!
[LOG 00:18:02.245] [BDArmory.VesselSpawnerBase]: Vessel Microraptor "Zlag" AIM-120 spawned!
[LOG 00:18:02.245] [BDArmory.VesselSpawnerBase]: Vessel Microraptor Rockets spawned!
[LOG 00:18:02.246] [BDArmory.VesselSpawnerBase]: Vessel Curtiss P-40M PussyFugl spawned!
[LOG 00:18:02.437] DEBUG vessel Mark2Cockpit (Microraptor AIM-9) (Vessel) is packed at time 63.76859
[LOG 00:18:02.437] [FLIGHT GLOBALS]: Switching To Vessel Microraptor AIM-9 ---------------------- 
[LOG 00:18:02.437] Packing SpawnProbe for orbit
[ERR 00:18:02.438] Exception handling event onVesselGoOnRails in class KerbalEVA:System.NullReferenceException: Object reference not set to an instance of an object
  at KerbalEVA.OnVesselGoOnRails (Vessel v) [0x00025] in <4deecb19beb547f19b1ff89b4c59bd84>:0 
  at EventData`1[T].Fire (T data) [0x000b0] in <4deecb19beb547f19b1ff89b4c59bd84>:0 
        UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogFormat(LogType, Object, String, Object[])
        UnityEngine.Debug:LogError(Object)
        EventData`1:Fire(Vessel)
        Vessel:Vessel.GoOnRails_Patch1(Vessel)
        FlightGlobals:setActiveVessel(Vessel, Boolean, Boolean)
        FlightGlobals:ForceSetActiveVessel(Vessel)
        BDArmory.UI.LoadedVesselSwitcher:ForceSwitchVessel(Vessel) (at /storage/github/BDArmory/BDArmory/UI/LoadedVesselSwitcher.cs:1324)
        BDArmory.Competition.VesselSpawning.<SpawnAllVesselsOnceCoroutine>d__10:MoveNext() (at /storage/github/BDArmory/BDArmory/Competition/VesselSpawning/CircularSpawning.cs:264)
        UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[EXC 00:18:02.440] NullReferenceException: Object reference not set to an instance of an object
        KerbalEVA.OnVesselGoOnRails (Vessel v) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
        EventData`1[T].Fire (T data) (at <4deecb19beb547f19b1ff89b4c59bd84>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:LogException(Exception)
        EventData`1:Fire(Vessel)
        Vessel:Vessel.GoOnRails_Patch1(Vessel)
        FlightGlobals:setActiveVessel(Vessel, Boolean, Boolean)
        FlightGlobals:ForceSetActiveVessel(Vessel)
        BDArmory.UI.LoadedVesselSwitcher:ForceSwitchVessel(Vessel) (at /storage/github/BDArmory/BDArmory/UI/LoadedVesselSwitcher.cs:1324)
        BDArmory.Competition.VesselSpawning.<SpawnAllVesselsOnceCoroutine>d__10:MoveNext() (at /storage/github/BDArmory/BDArmory/Competition/VesselSpawning/CircularSpawning.cs:264)
        UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[LOG 00:18:02.441] Packing Bob Kerman for orbit
[LOG 00:18:02.442] [PlanetariumCamera]: Focus: Microraptor AIM-9
[LOG 00:18:02.526] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part Mark2Cockpit (Microraptor AIM-9) on vessel Microraptor AIM-9
[LOG 00:18:02.528] [FlightIntegrator]: Vessel Microraptor AIM-9 has been unloaded 1.79769313486232E+308, applying analytic temperature 301.776826919045
[LOG 00:18:02.528] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part Mark2Cockpit (Microraptor Turret) on vessel Microraptor Turret
[LOG 00:18:02.529] [FlightIntegrator]: Vessel Microraptor Turret has been unloaded 1.79769313486232E+308, applying analytic temperature 301.682740890175
[LOG 00:18:02.529] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part miniIntake (Hang-time (wood) v3) on vessel Hang-time (wood) v3
[LOG 00:18:02.530] [FlightIntegrator]: Vessel Hang-time (wood) v3 has been unloaded 1.79769313486232E+308, applying analytic temperature 303.285090291873
[LOG 00:18:02.530] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part Mark2Cockpit (Microraptor "Zlag" AIM-120) on vessel Microraptor "Zlag" AIM-120
[LOG 00:18:02.531] [FlightIntegrator]: Vessel Microraptor "Zlag" AIM-120 has been unloaded 1.79769313486232E+308, applying analytic temperature 301.682391396614
[LOG 00:18:02.531] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part Mark2Cockpit (Microraptor Rockets) on vessel Microraptor Rockets
[LOG 00:18:02.532] [FlightIntegrator]: Vessel Microraptor Rockets has been unloaded 1.79769313486232E+308, applying analytic temperature 301.896584565358
[LOG 00:18:02.532] [FlightIntegrator]: Reloaded drag cube for zeroed cube root part oldfightercockpit (Curtiss P-40M PussyFugl) on vessel Curtiss P-40M PussyFugl
[LOG 00:18:02.533] [FlightIntegrator]: Vessel Curtiss P-40M PussyFugl has been unloaded 1.79769313486232E+308, applying analytic temperature 300.393772564189
[LOG 00:18:02.656] [Progress Node Reached]: RecordsAltitude
[LOG 00:18:02.658] [Progress Node Reached]: RecordsDistance
[LOG 00:18:04.660] [FLIGHT GLOBALS]: Switching To Vessel Hang-time (wood) v3 ---------------------- 
[LOG 00:18:04.662] [PlanetariumCamera]: Focus: Hang-time (wood) v3
[LOG 00:18:04.684] [KerbalSeat]: Boarded by Hang-time (wood) v3
[LOG 00:18:06.101] Unpacking Hang-time (wood) v3
[LOG 00:18:06.106] Unpacking Microraptor AIM-9
[LOG 00:18:06.118] Unpacking Microraptor Turret
[LOG 00:18:06.128] Unpacking Microraptor "Zlag" AIM-120
[LOG 00:18:06.139] Unpacking Microraptor Rockets
[LOG 00:18:06.152] Unpacking Curtiss P-40M PussyFugl
```
This is with the latest KSPCommunityFixes v1.20.1 from CKAN and was also occurring with v1.20.0.

~~Strangely, if I build this mod from the current master branch (21306a3) and copy those DLLs to my KSP install then the exception doesn't occur.~~ Edit: it does still occur, I just wasn't copying all the files across properly after building.

**Comment by NathanKell** [comment]
Presumably fixed in https://github.com/KSPModdingLibs/KSPCommunityFixes/commit/2a7c1405b2c0207a28006253febd1ac0fd1a87d6

**Comment by BrettRyland** [comment]
> Presumably fixed in [2a7c140](https://github.com/KSPModdingLibs/KSPCommunityFixes/commit/2a7c1405b2c0207a28006253febd1ac0fd1a87d6)

This is still present and unaffected by commit 2a7c140. Look for the "EXC" in [KSP.zip](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/9276495/KSP.zip).

**Comment by NathanKell** [comment]
Ah, based on your other issue I thought this was a new problem that occurred after updating to 1.20. Does it predate 1.20 then?

**Comment by BrettRyland** [comment]
I haven't tried earlier than 1.20.0 (I only found this mod recently) yet.

**Comment by BrettRyland** [comment]
With some educated guessing, I've narrowed this down to the PartStartStability patch being the cause of the issue.

**Comment by BrettRyland** [comment]
For context, the vessel spawning process in BDArmory takes several seconds to load in all the vessels and KSP likes to pack them at the end of the spawning process for some reason (I haven't figured out why yet as they should be within the physics range).
When switching to one of the vessels (the line:
```
[LOG 00:18:02.437] [FLIGHT GLOBALS]: Switching To Vessel Microraptor AIM-9 ----------------------
```
in the first post), KSP sees an EVA kerbal and automatically performs another vessel switch after a couple of seconds (the line:
```
[LOG 00:18:04.660] [FLIGHT GLOBALS]: Switching To Vessel Hang-time (wood) v3 ---------------------- 
```
in the first post). It'd be nice if it didn't perform that automatic switch, but that's a separate issue.

**Comment by gotmachine** [comment]
> KSP likes to pack them at the end of the spawning process for some reason (I haven't figured out why yet as they should be within the physics range

In any case, I would suggest trying to fix this. Having a vessel starting unpacked and then being packed in the next frame is likely to cause a lot of weird issues.

The PartStartStability patch is changing an unpredictable behavior into a more stable one, moving part initialization from Update to FixedUpdate, mainly to avoid an arbitrary amount of physics frames happening while the parts aren't initialized (notably preventing parts from drifting away before the joints holding them are created).

What is likely happening in your case is the EVA kerbal parts being fully initialized when the KSPCF patch is present, registering the OnVesselGoOnRails callback, but the KerbalFSM not being yet started when the callback is called. 

I could move the KerbalFSM init update-yielding coroutine to a fixedupdate-yielding coroutine and that might get ride of the exception, but TBH I think you actually have a wider issue on your hands, and this would only hide it under the rug.

**Comment by BrettRyland** [comment]
OK, I've been experimenting with the vessel spawning process in BDArmory and it turns out the culprit is actually due to switching the camera back from the spawn camera to the main camera too early, which presumably is messing with the floating origin (or similar) while EVA initialisation is happening and causing that exception. Waiting until after the vessels are unpacked before reverting the camera and switching to a vessel appears to prevent this exception.

Incidentally, what I wrote in the previous comment wasn't quite right: the vessels aren't getting packed after spawning, they simply haven't yet been unpacked when the vessel switch occurs. And this is still true when KSP automatically switches to the vessel with an EVA kerbal, i.e., that vessel is still packed when the switch occurs but it doesn't appear to be triggering the exception.

Would it be possible to prevent KSP from doing this automatic switch whenever a new vessel with an EVA kerbal is spawned?
This would be a boon for avoiding unwanted camera switches with the current bulk-spawning and the continuous spawning mode where individual craft are added to an active competition as others are destroyed.

**Comment by gotmachine** [comment]
> Would it be possible to prevent KSP from doing this automatic switch whenever a new vessel with an EVA kerbal is spawned?

It is likely possible, but I don't see why you can't implement it from your side. KSPCF tries very hard not to alter any stock behavior to prevent conflicts with mods relying on implementation details of the KSP codebase. We don't want to have to manage such hard to diagnose conflicts, but this can be a viable option for you.

**Comment by BrettRyland** [comment]
> It is likely possible, but I don't see why you can't implement it from your side. KSPCF tries very hard not to alter any stock behavior to prevent conflicts with mods relying on implementation details of the KSP codebase. We don't want to have to manage such hard to diagnose conflicts, but this can be a viable option for you.

I don't know how to implement it from my side since the automatic camera switching due to a newly spawned EVA kerbal is something that is triggered internally in KSP, presumably from something in `KerbalEVA.OnVesselGoOnRails`, but I don't know what. If you know how to disable that behaviour through the KSP API, then please let me know and I can include it where applicable in the vessel spawning code in BDArmory.

If it's not possible to disable the behaviour via the KSP API, then the only way I can see to disable it is via the approach that KSPCF takes, which would then require adding further dependencies to BDArmory (which is undesirable) and figuring out precisely what's being called, or if KSPCF could provide a toggle for disabling it then BDArmory could take advantage of this through reflection (thus not having a hard dependency on KSPCF and its dependencies) and temporarily disable it during vessel spawning.

**Comment by gotmachine** [comment]
> If you know how to disable that behaviour through the KSP API

I haven't looked at what you're trying to do, but it's likely that Harmony-patching is the only sane way to achieve it.

> the only way I can see to disable it is via the approach that KSPCF takes, which would then require adding further dependencies to BDArmory

Either way, you're adding new dependencies... It seems way more convoluted to have your mod relying on an optional KSPCF harmony patch specific to your mod (thus requiring 2 dependencies, KSPCF and Harmony), when you can just have that patch in your own codebase and only a dependency on Harmony.

**Comment by BrettRyland** [comment]
> Either way, you're adding new dependencies... It seems way more convoluted to have your mod relying on an optional KSPCF harmony patch specific to your mod (thus requiring 2 dependencies, KSPCF and Harmony), when you can just have that patch in your own codebase and only a dependency on Harmony.

The point is that it'd be an optional dependency, i.e., BDArmory could take advantage of it if it's present but doesn't require it in order to use BDArmory if the user doesn't want to install KSPCF for some reason (BDArmory has several such optional dependencies for dealing with mods like TweakScale, FAR and procedural wings/parts). And the reason I'd prefer it through KSPCF is because I don't have any experience with Harmony (which you guys clearly have), so I figured that'd be the easiest way forward.

In any case, it's not really a big deal, just something that'd be nice to have, so don't worry about it if it's not something easy to implement.

**Comment by gotmachine** [comment]
TBF there is also the fact that I don't have time to "do the work" on your behalf :P 

I would really suggest taking the time to learn using Harmony. Especially in the context of complex mods like BDA, it's a game changer that allow cleaner and faster code in many cases. It's relatively straightforward to learn, at least for basic prefix/postfix patches.

**Comment by BrettRyland** [comment]
> TBF there is also the fact that I don't have time to "do the work" on your behalf :P

Fair enough :-). Yeah, I'll look into learning Harmony. Thanks!
